repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.941"
    hooks:
      - id: mypy
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        language_version: python3
