version: 2.1

jobs:
  test-build:
    docker:
      - image: cimg/python:3.9.10
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt -r requirements-dev.txt
            python setup.py bdist_wheel
  run-tests:
    docker:
      - image: cimg/python:3.9.10
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt -r requirements-dev.txt
            coverage run --source=flowmancer -m pytest tests/
            coveralls
  bumpversion-patch:
    docker:
      - image: cimg/python:3.9.10
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "d7:4a:12:18:bc:6b:e1:50:5f:ab:92:0d:72:9a:d8:f3"
      - run:
          command: |
            git config user.name $CIRCLE_USERNAME
            git config user.email "lee.nathan.sh@outlook.com"
            pip install bump2version
            bumpversion --commit --message "[skip ci] Bump version: {current_version} → {new_version}" --tag patch
            git push && git push --tags
  deploy:
    docker:
      - image: cimg/python:3.9.10
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt -r requirements-dev.txt
            python setup.py bdist_wheel
            twine upload dist/*
workflows:
  on-commit:
    jobs:
      - test-build:
          filters:
            branches:
              only: /main/
      - run-tests:
          filters:
            branches:
              only: /main/
      - bumpversion-patch:
          requires:
            - test-build
            - run-tests
          filters:
            branches:
              only: /main/
  on-tag:
    jobs:
      - deploy:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
