version: 2.1
jobs:
  build-test:
    docker:
      - image: cimg/python:3.9.10
    steps:
      - checkout
      - run:
          command: |
            sudo pip3 install -r requirements.txt
            python3 setup.py bdist_wheel
      - run:
          command: |
            pytest
  deploy:
    docker:
      - image: cimg/python:3.9.10
    steps:
      - checkout
      - run:
          command: |
            sudo pip3 install -r requirements.txt
            python3 setup.py bdist_wheel
            twine upload dist/*
workflows:
  build-deploy:
    jobs:
      - build-test:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build-test
          filters:
            tags:
              only: /.*/