version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.6

jobs:
  build-test:
    docker:
      - image: cimg/python:3.9.10
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt -r requirements-dev.txt
            python setup.py bdist_wheel
      - run:
          command: |
            pytest
  bumpversion-patch:
    docker:
      - image: cimg/python:3.9.10
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "d7:4a:12:18:bc:6b:e1:50:5f:ab:92:0d:72:9a:d8:f3"
      - run:
          command: |
            pip install bump2version
            bumpversion --commit --message "[skip ci] Bump version: {current_version} → {new_version}" --tag patch
            git config user.name $CIRCLE_USERNAME
            git add -u
            git commit -m "[skip ci] Bump version: ${current_version} → ${new_version}"
  deploy:
    docker:
      - image: cimg/python:3.9.10
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt -r requirements-dev.txt
            python setup.py bdist_wheel
            twine upload dist/*
workflows:
  on-commit:
    jobs:
      - build-test:
          filters:
            branches:
              ignore: /.*/
      - bumpversion-patch:
          filters:
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - build-test
          filters:
            branches:
              ignore: /.*/
