version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.6

jobs:
  build-test:
    docker:
      - image: cimg/python:3.9.10
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt -r requirements-dev.txt
            python setup.py bdist_wheel
      - run:
          command: |
            pytest
  deploy:
    docker:
      - image: cimg/python:3.9.10
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt -r requirements-dev.txt
            python setup.py bdist_wheel
            twine upload dist/*
workflows:
  build-deploy:
    jobs:
      - build-test:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - build-test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
